if: branch !~ ^v\d
language: node_js
node_js: node
matrix:
  include:
  - dist: xenial
    after_script: node_modules/.bin/nyc report | npx coveralls
  - os: windows
    script: npx --no-install eslint .
